### ISSUE TITLE
Weird Popup UI?

### ISSUE THREAD

**Issue by seenoevo** [hsylife/SwiftyPickerPopover#83]
I am not using a `UIButton` to add an `IBAction` as shown in your example but have a `UITextField instead:

```
@IBAction func changeDate(_ sender: UITextField)
{
    DatePickerPopover(title: "DatePicker")
        .setDateMode(.date)
        .setSelectedDate(Date())
        .setValueChange(action: { _, selectedDate in
            print("current date \(selectedDate)")
        })
        .setDoneButton(action: { popover, selectedDate in print("selectedDate \(selectedDate)")})
        .setCancelButton(action: { _, _ in print("cancel")})
        .appear(originView: sender, baseViewController: self)
}
```

I am getting this weird popup with a black background where the `Cancel` and `Done` buttons are, **AND** I am also not seeing the background greyed out:
![untitled](https://user-images.githubusercontent.com/8109158/40041753-f0bdf668-57d3-11e8-978b-f8b5d2c9dec8.png)

What might my issue possibly be?

**Comment by hsylife** [comment]
Weird. I need more time to figure out the reason! I will reply to you ASAP.

**Comment by seenoevo** [comment]
Cool, I'm glad it's not just me :)

**Comment by hsylife** [comment]
I guess you call `UINavigationBar.appearance().barTintColor = UIColor.black` in AppDelegate.

Anyway, this is a bug. We need to add more code into the repos. In open func appear(originView: UIView, baseViewWhenOriginViewHasNoSuperview: UIView? = nil, baseViewController: UIViewController, completion:(()->Void)? = nil),

```
navigationController.popoverPresentationController?.backgroundColor = self.backgroundColor ?? self.baseViewController?.navigationController?.navigationBar.barTintColor ?? self.baseViewController?.view.backgroundColor
 ```

I will add it to the official master asap.
Thank you for your report!

**Comment by hsylife** [comment]
The fix has been available on brach "6.2.1".

**Comment by hsylife** [comment]
@seenoevo OK. Now the fixed version has been available. Please check it up!

**Comment by seenoevo** [comment]
@hsylife yes the sample project works with a `UITextField` but incorporating it into my project still has the same issue as in the screenshot.

I have no idea why the issue still exist in my project, because I pulled the latest changes from your library.

My project has a lot of code. Give me some time and I'll provide you with a stripped-down version of my project with the issue.

Maybe you can inspect it and find the cause?

Thanks!

**Comment by hsylife** [comment]
How do you set your navigation bar color?

**Comment by seenoevo** [comment]
thanks for the direction, the problem is here:

```
func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool {
    // Override point for customization after application launch.
    
    // Change all navigation bar color to white
    UINavigationBar.appearance().barStyle = .blackOpaque
    
    // Change all navigation bar title font and color
    UINavigationBar.appearance().titleTextAttributes = [ NSAttributedStringKey.foregroundColor: UIColor.white,
                                                         NSAttributedStringKey.font: UIFont(name: GlobalAccessor.fontFuturaMedium,
                                                                                            size: 20)! ]
    
    return true
}
```

I set my status bar text as well as navigation bar items text, which causes the issue with the pop-up.

Commenting the two code out gives the following:

![simulator screen shot - iphone 7 - 2018-05-20 at 14 43 40](https://user-images.githubusercontent.com/8109158/40283993-3d0c415c-5c3c-11e8-8ef7-b43923b897b2.png)

However, I need to keep the above code due to the navigation bar color, which makes the text harder to read.

Maybe you can change `UINavigationBar.appearance().barStyle = .default` when the pop-up occurs, so that the status bar text is black and revert it back once dismiss?

I've attached a sample project: 
[TestProject.zip](https://github.com/hsylife/SwiftyPickerPopover/files/2020737/TestProject.zip)

**Comment by hsylife** [comment]
Thank you for sharing your code. I will inspect it.

**Comment by hsylife** [comment]
Finally, I've reached to the goal.
![simulator screen shot - iphone 8 plus - 2018-05-21 at 09 09 12](https://user-images.githubusercontent.com/11023238/40285417-a7b704d4-5cd6-11e8-99fc-928883b9a68a.png)

Give me some time to update the repo.
I'm going to fix my repo on my lunch time today as possible...

**Comment by hsylife** [comment]
I've released 6.3.1. Please try it.

**Comment by seenoevo** [comment]
confirmed working now!

**Comment by hsylife** [comment]
Hello, @seenoevo 
I'm happy to hear that you've confirmed it's working.

And, I think that your note contains a proposal. So, I'd like you to make another proposal issue.

Anyway, you can folk it and manipulate it as the following:
```
// AbstractPickerPopoverViewController.swift

func popoverPresentationControllerShouldDismissPopover(_ popoverPresentationController: UIPopoverPresentationController) -> Bool {
     return false // Prevent dismissing by tapping outside of the popover
}
```

I should make a new setting method based on your idea...

**Comment by hsylife** [comment]
Finally, I've implemented our new func, setOutsideTappingDismissing().
It's available on the branch. https://github.com/hsylife/SwiftyPickerPopover/tree/feature/prevent-dismiss-by-tapping-outside

I will merge it into the master after adding README/CHANGELOG description and updating version numbers asap

**Comment by seenoevo** [comment]
@hsylife great!

I think this will serve well for other users also, not just me!

As always, thanks for the prompt response and fixes!

**Comment by seenoevo** [comment]
I hate to come back to this issue again, but I just update the pod from the sample project I attached, and this is the result I'm getting:

![simulator screen shot - iphone 7 - 2018-05-27 at 18 05 55](https://user-images.githubusercontent.com/8109158/40592850-a8e313aa-61d8-11e8-996d-8af589854245.png)

**Comment by hsylife** [comment]
What is the issue? Popover background color, maybe?

**Comment by hsylife** [comment]
I will check it up

**Comment by seenoevo** [comment]
Yes the background containing the date, it should be white as you have shown above when you mentioned you fixed the bug, but in the latest version, it's the same color as the navigation bar.

**Comment by hsylife** [comment]
Thank you for your reply. And this is my faults. I will inspect it at tonight.

**Comment by hsylife** [comment]
It was my fault. I've published the fixed version as (6.5.2). Please update to the version.

**Comment by seenoevo** [comment]
hi @hsylife 

I appear to have an issue related to this fix you made again. It's not your fault as you most likely tested this in the simulator, and I don't have this issue when running the latest v6.5.2 on my iPhone 7 simulator also.

But when I ran this on a real iPhone 7 device, I get a constraint warning when the popover occurs:

> [LayoutConstraints] Unable to simultaneously satisfy constraints.
> 	Probably at least one of the constraints in the following list is one you don't want. 
> 	Try this: 
> 		(1) look at each constraint and try to figure out which you don't expect; 
> 		(2) find the code that added the unwanted constraint or constraints and fix it. 
> (
>     "<NSLayoutConstraint:0x170095d60 UIButton:0x100d24ce0'Clear'.height == 30   (active)>",
>     "<NSLayoutConstraint:0x1700954f0 'UISV-hiding' UIButton:0x100d24ce0'Clear'.height == 0   (active)>"
> )
> 
> Will attempt to recover by breaking constraint 
> <NSLayoutConstraint:0x170095d60 UIButton:0x100d24ce0'Clear'.height == 30   (active)>
> 
> Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
> The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.

I tried v6.4.0 on my device and this warning does not occur.

If you have a real device, can you please test the sample project on the device and see what's causing this constraint conflict?
